apiVersion: v1
kind: Service
metadata:
  name: vprosearch01
spec:
  type: ClusterIP
  selector:
    app: vprosearch01
  ports:
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200 