apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  type: ClusterIP
  selector:
    app: vprocache01
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache02
spec:
  type: ClusterIP
  selector:
    app: vprocache02
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211 